format = "$status$time$cmd_duration$line_break$all$line_break$character"

[cmd_duration]
format = "took [$duration]($style) "
style = "bold blue"

[direnv]
disabled = false

[git_branch]
symbol = "ïˆ "

[git_status]
style = "bold purple"

[status]
disabled = false
format = "[$symbol]($style) "
success_symbol = "ğŸŸ¢"

[time]
disabled = false
format = "at [$time]($style) "
